resource-group-basename = "terraproject"
basename = "terraproject"
acr-basename = "terraproject1647969850235"
virtual-network-main-address-space = "10.0.0.1/24"
deployment-environment = "dllo"
company-identifier = "seg"
